name: neo_nest
description: A smart baby monitoring Flutter app.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  url_launcher: ^6.2.6
  audioplayers: ^6.5.0
  shared_preferences: ^2.2.1
  just_audio: ^0.9.35
  audio_session: ^0.1.10
  flutter_sound: ^9.2.13
  permission_handler: ^11.2.0
  path_provider: 2.1.5
  http: ^1.4.0
  file_picker: ^6.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/audio/
    - assets/images/baby_home.jpg